import type { Product } from "../types/product";
import type { Category } from "../types/category";
import type { Brand } from "../types/brand";

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    sku: "IP15PM-256",
    category: "Smartphone",
    brand: "Apple",
    purchasePrice: 1020,
    sellingPrice: 1199,
    stock: 18,
    status: "In Stock",
    warranty: "1 Year",
  },
  {
    id: "2",
    name: "iPhone 15 Pro",
    sku: "IP15P-128",
    category: "Smartphone",
    brand: "Apple",
    purchasePrice: 880,
    sellingPrice: 999,
    stock: 9,
    status: "In Stock",
    warranty: "1 Year",
  },
  {
    id: "3",
    name: "Samsung Galaxy S24 Ultra",
    sku: "SGS24U-256",
    category: "Smartphone",
    brand: "Samsung",
    purchasePrice: 940,
    sellingPrice: 1099,
    stock: 12,
    status: "In Stock",
    warranty: "1 Year",
  },
  {
    id: "4",
    name: "Samsung Galaxy S24",
    sku: "SGS24-256",
    category: "Smartphone",
    brand: "Samsung",
    purchasePrice: 650,
    sellingPrice: 799,
    stock: 6,
    status: "Low Stock",
    warranty: "1 Year",
  },
  {
    id: "5",
    name: "Google Pixel 9 Pro",
    sku: "GP9P-128",
    category: "Smartphone",
    brand: "Google",
    purchasePrice: 750,
    sellingPrice: 899,
    stock: 5,
    status: "Low Stock",
    warranty: "1 Year",
  },
  {
    id: "6",
    name: "OnePlus 13",
    sku: "OP13-256",
    category: "Smartphone",
    brand: "OnePlus",
    purchasePrice: 620,
    sellingPrice: 749,
    stock: 14,
    status: "In Stock",
    warranty: "1 Year",
  },
  {
    id: "7",
    name: "AirPods Pro 2",
    sku: "APP2-USB",
    category: "Accessories",
    brand: "Apple",
    purchasePrice: 190,
    sellingPrice: 249,
    stock: 31,
    status: "In Stock",
    warranty: "6 Months",
  },
  {
    id: "8",
    name: "Galaxy Buds 3 Pro",
    sku: "GB3P-001",
    category: "Accessories",
    brand: "Samsung",
    purchasePrice: 150,
    sellingPrice: 199,
    stock: 3,
    status: "Low Stock",
    warranty: "6 Months",
  },
  {
    id: "9",
    name: "Apple 20W USB-C Adapter",
    sku: "AP20W-USB",
    category: "Accessories",
    brand: "Apple",
    purchasePrice: 15,
    sellingPrice: 24,
    stock: 0,
    status: "Out of Stock",
    warranty: "6 Months",
  },
  {
    id: "10",
    name: "Samsung 45W Charger",
    sku: "SM45W-001",
    category: "Accessories",
    brand: "Samsung",
    purchasePrice: 25,
    sellingPrice: 39,
    stock: 22,
    status: "In Stock",
    warranty: "6 Months",
  },
];



export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Smartphone",
    description: "Mobile phones and smartphones",
    status: "Active",
    createdAt: "2026-01-12",
  },
  {
    id: "cat-2",
    name: "Accessories",
    description: "Phone accessories and peripherals",
    status: "Active",
    createdAt: "2026-01-15",
  },
  {
    id: "cat-3",
    name: "Tablet",
    description: "Tablets and large screen devices",
    status: "Active",
    createdAt: "2026-02-03",
  },
  {
    id: "cat-4",
    name: "Laptop",
    description: "Laptops and notebooks",
    status: "Active",
    createdAt: "2026-02-10",
  },
  {
    id: "cat-5",
    name: "Smartwatch",
    description: "Smart watches and wearable devices",
    status: "Inactive",
    createdAt: "2026-02-18",
  },
];



export const brands: Brand[] = [
  {
    id: "brand-1",
    name: "Apple",
    description: "Apple smartphones and accessories",
    status: "Active",
    createdAt: "2026-01-10",
  },
  {
    id: "brand-2",
    name: "Samsung",
    description: "Samsung smartphones and electronics",
    status: "Active",
    createdAt: "2026-01-12",
  },
  {
    id: "brand-3",
    name: "OnePlus",
    description: "OnePlus smartphones and accessories",
    status: "Active",
    createdAt: "2026-01-18",
  },
  {
    id: "brand-4",
    name: "Google",
    description: "Google Pixel smartphones and devices",
    status: "Active",
    createdAt: "2026-02-02",
  },
  {
    id: "brand-5",
    name: "Xiaomi",
    description: "Xiaomi phones and smart devices",
    status: "Active",
    createdAt: "2026-02-08",
  },
  {
    id: "brand-6",
    name: "Huawei",
    description: "Huawei smartphones and accessories",
    status: "Inactive",
    createdAt: "2026-02-15",
  },
];